/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:00cf411e-5dfb-4c2d-8daa-91e18df317cb",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_LE8I1QDzn",
    "aws_user_pools_web_client_id": "5pqmehlj649h5cg4ae2uupt5sa",
    "oauth": {}
};


export default awsmobile;
